exclude:
  
  
- node_modules
  - .gitignore
  - .DS_Store
  - npm-debug.log
  - yarn-debug.log
  - yarn-error.log

# Adicione outras configurações do Jekyll aqui, se necessário
title: Financas
description: "Site de organização financeira"
baseurl: "https://github.com/vitormuniz0/financas" # ou o subdiretório, se houver
url: "" # substitua pela URL base do seu site
theme: jekyll-theme-primer