exclude:
  - node_modules
  - .gitignore
  - .DS_Store
  - npm-debug.log
  - yarn-debug.log
  - yarn-error.log
  - /financas/node_modules
  - /server/node_modules

# Adicione outras configurações do Jekyll aqui, se necessário
title: Financas
description: "Site de organização financeira"
baseurl: "/financas" # ajuste conforme necessário
url: "https://vitormuniz0.github.io/financas/" # substitua pela URL base do seu site
theme: jekyll-theme-primer
