exclude:
  - node_modules
  
  
- .gitignore
  - .DS_Store
  - npm-debug.log
  
 
- yarn-debug.log
  
 
- yarn-error.log

name: Build and Deploy Jekyll site

on:
  push:
    
  
branches:
      
   
- main

jobs:
  
 
build:
    
   
runs-on: ubuntu-latest

    

   


steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        
 
uses: actions/setup-ruby@v2
        
     
with:
          
 
ruby-version: '3.1'

      

  
- name: Install Bundler
        
        
run: gem install bundler

      

- name: Install dependencies
        
     
run: bundle install

      

- name: Build the site
        
  
run: bundle exec jekyll build
